site_name: COI-Guide
site_description: 'Όλα τα resources που χρειάζεστε για την Ολυμπιάδα Πληροφορικής'
docs_dir: docs/
repo_name: 'coinformatics/coi-guide'
repo_url: 'https://github.com/coinformatics/coi-guide'
site_url: 'https://coinformatics.github.io/coi-guide'
edit_uri: blob/main/docs/
plugins:
  - search
  - social
  - tags
theme:
  name: 'material'
  features:
    - content.tooltips
  palette:
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  icon:
    tag:
      seg: material/family-tree
      dp: material/chart-tree
      interactive: material/swap-horizontal
      maths: material/calculator
      graphs: fontawesome/solid/circle-nodes
      sqrt: material/square-root
extra:
  tags:
    Segment Trees: seg
    Dynamic Programming: dp
    Interactive Problems: interactive
    Mathematics: maths
    Graphs: graphs
    SQRT Decomposition: sqrt

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - abbr
  - attr_list
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details



extra_javascript:
  - https://code.jquery.com/jquery-3.5.1.min.js
  - javascripts/mathjax.js
  - javascripts/author.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
