site_name: COI-Guide
site_description: 'Όλα τα resources που χρειάζεστε για την Ολυμπιάδα Πληροφορικής'
docs_dir: docs/
repo_name: 'coinformatics/coi-guide'
repo_url: 'https://github.com/coinformatics/coi-guide'
theme:
  name: 'material'
plugins:
  - search
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md


extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

